version: "3"
services:
  frontend:
    image: node:16.17.0
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      sh -c '
        echo "installing packages... (This may takes few minuites)"
        npm install &&
        echo "install completed!"
        npm start
      '
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
